### ISSUE TITLE
rtnetlink: add support for the nexthops API

### ISSUE THREAD

**Issue by mdlayher** [jsimonetti/rtnetlink#107]
See this presentation: https://linuxplumbersconf.org/event/4/contributions/434/attachments/251/436/nexthop-objects-talk.pdf.

I'll work on this!

**Comment by mdlayher** [comment]
Sorry all, I ended up not needing this for my project. Others are welcome to implement it as necessary though.

**Comment by jsimonetti** [comment]
I'll close this issue for now, we can always reopen if needed.
