### ISSUE TITLE
Please create a release of rtnetlink

### ISSUE THREAD

**Issue by bdrung** [jsimonetti/rtnetlink#134]
rtnetlink is packaged for Debian: https://tracker.debian.org/pkg/golang-github-jsimonetti-rtnetlink. There are no release to follow. So it is unknown when we should update the package and if it is safe to update. Please create a first release. In case you are unfamiliar with it, you can read about versioning here (since the version number have a meaning):

* https://go.dev/doc/modules/version-numbers
* https://go.dev/doc/modules/release-workflow

**Comment by jsimonetti** [comment]
I just tagged version v1.0.0.

**Comment by bdrung** [comment]
Thanks.
