### ISSUE TITLE
incorrect size, want: 184 or 192

### ISSUE THREAD

**Issue by maxpain** [jsimonetti/rtnetlink#145]
Hello.
On Linux 5.19.3 I'm getting this error: `incorrect size, want: 184 or 192` in `conn.Link.List()`

**Comment by jsimonetti** [comment]
Hi,

Could you elaborate please under which circumstance you get this error? Some steps to reproduce would be very helpful.
Much appreciated!

**Comment by maxpain** [comment]
@jsimonetti Actually, I use [Talos Linux](https://talos.dev), and tried to build it with Linux 5.19, when booting I got this error from [this function](https://github.com/siderolabs/talos/blob/master/internal/app/machined/pkg/controllers/network/link_status.go#L145).
Linux 5.15 (which is the default for this distro) and 5.18 (my custom-built kernel) work just fine.

**Comment by jsimonetti** [comment]
Have you tried contacting the talos devs about this? Is 5.19 something they support?
Mind youe, we have worked closely in the past so if this is something that is wrong in my lib I have no problem fixing it. I am not trying to wave away that there might be a problem, however this is the first time I hear about this issue and have not done any tests yet with 5.19.

**Comment by maxpain** [comment]
Unfortunately, they don't officially support 5.19, so I need to build Talos with this kernel by myself :(

**Comment by maxpain** [comment]
Anyway, Linux 5.19 is the stable and mainline kernel. Could you test your lib with this?

**Comment by maxpain** [comment]
@jsimonetti Thank you for understanding!

**Comment by jsimonetti** [comment]
@maxpain are you able to test if #146 fixes your issue?

**Comment by maxpain** [comment]
Yes, it's working, thank you!
