### ISSUE TITLE
RFC: no default link attributes when marshalling

### ISSUE THREAD

**Issue by insomniacslk** [jsimonetti/rtnetlink#18]
This is a request for comments. This library sets various default attributes when serializing a LinkMessage. I am no netlink expert but I noticed that this leads to errors when, for example, bringing an interface up or down, specifically `netlink receive: invalid argument`. I observed that `ip` doesn't send any attribute, and that's the only difference between a successful and an unsuccessful run. The `strace` output from the sample code below compares the output produced by `ip link set eth0 up` vs. the Go program at the end. The only difference is the presence of various attributes.
Furthermore, these attributes are serialized from the zero-value of the `LinkAttributes` structure, which leads to erroneous values.
I am proposing here to change the default behaviour to *not* serialize attributes if none is explicitly specified. With such change, the program below succeeds.

## Strace output
Using `ip`:
```
$ sudo strace -esendmsg ip link set wlan0 up
sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=32, type=RTM_NEWLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1554819541, pid=0}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("wlan0"), ifi_flags=IFF_UP, ifi_change=0x1}}, iov_len=32}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
+++ exited with 0 +++
```
while using this library I get:
```
$ go build && sudo strace -esendmsg ./example wlan0
sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=72, type=RTM_SETLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=2960429762, pid=16588}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("wlp2s0"), ifi_flags=0, ifi_change=0x1}, [{{nla_len=6, nla_type=IFLA_UNSPEC}, "\x00\x00"}, {{nla_len=5, nla_type=IFLA_IFNAME}, ""}, {{nla_len=8, nla_type=IFLA_MTU}, 0}, {{nla_len=8, nla_type=IFLA_LINK}, 0}, {{nla_len=5, nla_type=IFLA_QDISC}, ""}]}, iov_len=72}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
2019/04/09 15:44:08 netlink receive: invalid argument
panic: netlink receive: invalid argument
```

## Code of the failing program

```go
package main

import (
	"log"
	"net"

	"github.com/jsimonetti/rtnetlink"
	"golang.org/x/sys/unix"
)

func main() {
	conn, err := rtnetlink.Dial(nil)
	if err != nil {
		log.Panic(err)
	}
	iface, err := net.InterfaceByName("wlan0")
	if err != nil {
		log.Panic(err)
	}
	err = conn.Link.Set(&rtnetlink.LinkMessage{
		Family: unix.AF_UNSPEC,
		Type:   unix.ARPHRD_NETROM,
		Index:  uint32(iface.Index),
		Flags:  unix.IFF_UP,
		Change: unix.IFF_UP,
	})
	if err != nil {
		log.Panic(err)
	}
}
```

**Comment by jsimonetti** [comment]
This looks like rtnetlink weirdness.
If I look at the strace from the `ip` tool, the actuall message type is `RTM_NEWLINK`. Your example uses `RTM_SETLINK`.

If I change your example to use `conn.Link.New` without changing anything else this would as expected and identical to the `ip` tool.

**Comment by jsimonetti** [comment]
While I agree we should change the marshaling to ignore unset/unused attributes, this appears not to be a bug.

**Comment by insomniacslk** [comment]
I am also confused. I tried using RTM_NEWLINK too in a previous test, and I got this error, `netlink receive: file exists`, which I assume you're not seeing on your end

**Comment by jsimonetti** [comment]
No, I am not seeing this. However I did only test using a dummy interface: `sudo ip link add dummy0 type dummy` and then change your example to use dummy0 and a RTM_NEWLINK message.
Are you saying you can reproduce this? If so, then perhaps this is a bug after all.

Actually, I just tested `conn.Link.Set` on a dummy interface and this works fine too.

```
# sudo strace -esendmsg ./example
sendmsg(3, {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=12, msg_iov=[{iov_base={{len=72, type=RTM_SETLINK, flags=NLM_F_REQUEST|NLM_F_ACK, seq=1510735148, pid=11524}, {ifi_family=AF_UNSPEC, ifi_type=ARPHRD_NETROM, ifi_index=if_nametoindex("dummy0"), ifi_flags=IFF_UP, ifi_change=0}, [{{nla_len=6, nla_type=IFLA_UNSPEC}, "\x00\x00"}, {{nla_len=5, nla_type=IFLA_IFNAME}, ""}, {{nla_len=8, nla_type=IFLA_MTU}, 0}, {{nla_len=8, nla_type=IFLA_LINK}, 0}, {{nla_len=5, nla_type=IFLA_QDISC}, ""}]}, iov_len=72}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 72
+++ exited with 0 +++
```
```
# dmesg | tail -1
[ 1018.452014] IPv6: ADDRCONF(NETDEV_CHANGE): dummy0: link becomes ready
```

**Comment by jsimonetti** [comment]
Ok, so I have done some additional testing and I see the same behaviour as you do. I also concluded not sending LinkAttributes fixes this.
So this is definately a bug of this library.

**Comment by insomniacslk** [comment]
thanks a million @jsimonetti !
