### ISSUE TITLE
NeighAttributes does not appear to support non-Ethernet link-layer addresses

### ISSUE THREAD

**Issue by dswarbrick** [jsimonetti/rtnetlink#182]
Poking around in the code, I see that NeighAttributes.decode() expects link-layer addresses to be six bytes (i.e. Ethernet MAC addresses).

```go
func (a *NeighAttributes) decode(ad *netlink.AttributeDecoder) error {
	for ad.Next() {
		switch ad.Type() {
...
		case unix.NDA_LLADDR:
			if len(ad.Bytes()) != 6 {
				return errInvalidNeighMessageAttr
			}
			a.LLAddress = ad.Bytes()
...
```

It would be nice if this also supported other lengths supported by net.ParseMAC(), such as 20-byte InfiniBand link-layer addresses, allowing this package to be used in IPoIB environments.

**Comment by jsimonetti** [comment]
This was an easy fix.

Thanks for reporting it!

**Comment by dswarbrick** [comment]
Wow, awesome! Thank you very much for the rapid response!

**Comment by jsimonetti** [comment]
My pleasure. I'll tag a new release in a minute.
