### ISSUE TITLE
rtnl: new high level wrapper package

### ISSUE THREAD

**Issue by mdlayher** [jsimonetti/rtnetlink#40]
From an issue on the DHCP package:

> After a chat with @jsimonetti we agreed we'll go for an optional rtnl package under the jsimonetti/rtnetlink repo

This issue can track the implementation of that code.

It's a nit but I'm not sure it'll be entirely clear what differentiates rtnetlink and rtnl by name alone. I had thought of rtnlquick or similar, but ultimately good documentation should be helpful for clarifying the differences.

**Comment by insomniacslk** [comment]
Context at https://github.com/insomniacslk/dhcp/pull/271

**Comment by insomniacslk** [comment]
> It's a nit but I'm not sure it'll be entirely clear what differentiates rtnetlink and rtnl by name alone

My plan is to also provide a diagram that explains the stack:
```
jsimonetti/rtnetlink/rtnl : high level rtnetlink API (or whatever better name)
  ^
  |
jsimonetti/rtnetlink : low level rtnetlink API
  ^
  |
mdlayher/netlink : netlink IPC API
```

**Comment by yupi** [comment]
What about "jsimonetti/rtnetlink/simple"?
Just my 2¢.

**Comment by mdlayher** [comment]
"simple" is too general of a package name. If you came across "simple.Conn" in code, what would that mean to you?

The prefix is essential IMHO, for the same reason we don't call packages "client", "server", or "util".

**Comment by insomniacslk** [comment]
I completely agree with @mdlayher . Additionally, the goal here is not to be "simple" but to be at a higher level of abstraction. I think `rtnetlink` is already simple, and hopefully `rtnl` will be simple too :)

**Comment by yupi** [comment]
There are many subpackages with "client", "server" names.

Such a package can be imported qualified like:
`import rtnl "github.com/jsimonetti/rtnetlink/simple`

This way we shift the responsibility to create a good name to the end user :)

**Comment by mdlayher** [comment]
> There are many subpackages with "client", "server" names.

That certainly doesn't mean it's a good idea.

> This way we shift the responsibility to create a good name to the end user :)

This is an indication that the package was poorly named to begin with. I strongly disagree that this is a good idea.

**Comment by insomniacslk** [comment]
Oh you're right! I forgot it's a holiday here too, that explains why my calendar was empty :D . What about Tuesday 30th at 5 PM? Otherwise Wednesday 11 AM? 

Andrea

**Comment by yupi** [comment]
> > There are many subpackages with "client", "server" names.
> 
> That certainly doesn't mean it's a good idea.

IMHO, depends on how to look at it. I would argue what I can get the idea what "github.com/jsimonetti/rtnetlink/simple" is about but not with "github.com/jsimonetti/rtnetlink/rtnl".
Sure if looking at subpackage name alone "simple" doesn't make any sense.

Subpackages like "client", "server" are common for big packages like k8s or docker. Guess rtnetlink doesn't qualify for such naming scheme.

> 
> > This way we shift the responsibility to create a good name to the end user :)
> 
> This is an indication that the package was poorly named to begin with. I strongly disagree that this is a good idea.

**Comment by insomniacslk** [comment]
fixed by #44

**Comment by insomniacslk** [comment]
One more thing before closing maybe - I just noticed that `rtnl.Close` doesn't return errors[1], while the underlying implementation does[2]. I think we should not swallow the error, and return it instead.

[1] https://github.com/jsimonetti/rtnetlink/blob/master/rtnl/conn.go#L31
[2] https://github.com/mdlayher/netlink/blob/master/conn.go#L98

**Comment by yarikk** [comment]
Who checks for Close() errors I wonder…

**Comment by insomniacslk** [comment]
There's plenty of documentation on why not checking errors on close is wrong, I can look something up if you want. On sockets it's not as problematic as on writable files, but it's a good norm, and I'm not a fan of "but who checks for close errors" - if it returns an error, there's a reason.

As per the deferred call - `defer` is a Go thing. Calling defer and ignoring the return value (especially on writable files) can hide problems. The fact that it became a common pattern to just defer and ignore errors doesn't make it less of an error. Also, `defer` is not the only mean to call `Close` - you may want to close immediately without waiting until the end of the function.

An example of dealing with Close errors:
```
defer func() {
    if err := conn.Close(); err != nil {
        log.Printf("error closing netlink connection: %v", err)
    }
}
```

Even better, capture the error at defer time and report to the caller

**Comment by insomniacslk** [comment]
I found this article, https://www.joeshaw.org/dont-defer-close-on-writable-files/ . 

It explains the problem nicely, clarifies that this is an issue only in certain scenarios (e.g. writable files), and offers a nice solution using `defer`, anonymous functions, and named return values.

In short:
```
func helloNotes() (err error) {
    var f *os.File
    f, err = os.Create("/home/joeshaw/notes.txt")
    if err != nil {
        return
    }

    defer func() {
        cerr := f.Close()
        if err == nil {
            err = cerr
        }
    }()

    err = io.WriteString(f, "hello world")
    return
}
```

**Comment by insomniacslk** [comment]
Thanks @yarikk ! I'll go ahead and close this issue (reopen if necessary)
